data:
  dataset_name: scifact
  output_folder: ./generated_improved

query_writer:
  queries_per_passage: -1
  batch_size: 8
  augmented: None
  use_train_qrels: False
  top_p: 0.95
  top_k: 25
  max_length: 64
  augment_probability : 1.0
  forward_model_path: Helsinki-NLP/opus-mt-en-fr
  back_model_path: Helsinki-NLP/opus-mt-fr-en
  augment_per_query : 2
  augment_temperature : 2.0

hard_negative_miner:
  negatives_per_query: 50
  query_augment_mod: None
  models: ["msmarco-distilbert-base-v3", "msmarco-MiniLM-L-6-v3"]
  score: [cos_sim, cos_sim]
  use_train_qrels: False

trainer:
  cross_encoders : ["cross-encoder/ms-marco-electra-base"]
  bi_retriver : GPL/msmarco-distilbert-margin-mse
  t_total: 140000
  eval_every: 10000
  batch_size: 32
  warmup_steps: 1000
  amp_training: True
  evaluate_baseline: False
  max_seq_length: 350
  seed: 1
  name: scifact_no_aug_electra_teacher