trainer:
  cross_encoders : ["cross-encoder/ms-marco-MiniLM-L-6-v2"]
  bi_retriver : GPL/msmarco-distilbert-margin-mse
  bi_retriver_name: mini_lm
  reducer : average
  t_total: 140000
  eval_every: 10000
  batch_size: 32
  warmup_steps: 1000
  amp_training: True
  evaluate_baseline: True
  max_seq_length: 350
  seed: 1
  name: ${query_writer.augmented}_${trainer.bi_retriver_name}_${trainer.reducer}